Week 2 -Chapter 2 - Live Class 2

In [11]:
import numpy as np

In [2]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [4]:
#identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
2*np.eye(5)

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

In [6]:
#It creates an instance of ndarray with evenly spaced values and returns the reference to it.

np.arange(1,7)
np.arange(1,7,2)

array([1, 3, 5])

In [7]:
np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a = np.array([[3,2],[1,5]])
b = np.array([[2,2],[7,5]])

In [9]:
a

array([[3, 2],
       [1, 5]])

In [10]:
b

array([[2, 2],
       [7, 5]])

In [11]:
#know the matrix shape
a.shape

(2, 2)

In [12]:
#used for matrix multiplication
np.dot(a,b)

array([[20, 16],
       [37, 27]])

In [13]:
#same function
a@b

array([[20, 16],
       [37, 27]])

In [14]:
np.multiply(np.dot(a,b),a)

array([[ 60,  32],
       [ 37, 135]])

The shares of three companies A, B, and C are $1 million, $800,000, and $500,000, respectively. We want to find the total amount required to purchase 3, 4, and 5 shares of these stocks, respectively.


In [15]:
P = np.array([[100], [80], [50]]) 
N = np.array([[3], [4], [5]])

In [16]:
N

array([[3],
       [4],
       [5]])

In [17]:
P

array([[100],
       [ 80],
       [ 50]])

In [18]:
N.shape

(3, 1)

In [19]:
P.shape

(3, 1)

In [20]:
total = np.dot(N.T,P)

In [21]:
total

array([[870]])

In [28]:
z = np.array([[2,0],[0,1]])

In [29]:
z

array([[2, 0],
       [0, 1]])

In [30]:
#the inverse of matrix
zinv = np.linalg.inv(z)

In [31]:
zinv

array([[0.5, 0. ],
       [0. , 1. ]])

In [1]:
from sklearn.datasets import load_digits
x = load_digits().data

In [2]:
#tells us the dimensionality of the code
x.ndim

2

In [3]:
x.shape

(1797, 64)

In [4]:
#the number of data
x.size

115008

In [5]:
x[20].shape

(64,)

In [6]:
x[0][3]

13.0

In [8]:
#the row 0
x[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [9]:
x[9]

array([ 0.,  0., 11., 12.,  0.,  0.,  0.,  0.,  0.,  2., 16., 16., 16.,
       13.,  0.,  0.,  0.,  3., 16., 12., 10., 14.,  0.,  0.,  0.,  1.,
       16.,  1., 12., 15.,  0.,  0.,  0.,  0., 13., 16.,  9., 15.,  2.,
        0.,  0.,  0.,  0.,  3.,  0.,  9., 11.,  0.,  0.,  0.,  0.,  0.,
        9., 15.,  4.,  0.,  0.,  0.,  9., 12., 13.,  3.,  0.,  0.])

In [7]:
x[0] == x[9]

array([ True,  True, False, False, False, False,  True,  True,  True,
       False, False, False, False, False, False,  True,  True,  True,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False,  True,  True,  True, False, False, False, False,  True,
        True])

In [10]:
x[0].max()

15.0

In [11]:
x[0].min()

0.0

In [14]:
#cosine similarity between img 0 and img 9, the first image and the tenth image  
x[0]@x[9]

2807.0

In [17]:
np.dot(x[0],x[9])

2807.0

In [20]:
#matrix of similarity (between the whole dataset)
matrix = x@x.T

In [21]:
matrix

array([[3070., 1866., 2264., ..., 2812., 3006., 2898.],
       [1866., 4209., 3432., ..., 3906., 3083., 3307.],
       [2264., 3432., 4388., ..., 4005., 3063., 3697.],
       ...,
       [2812., 3906., 4005., ..., 5092., 3729., 4598.],
       [3006., 3083., 3063., ..., 3729., 4316., 3850.],
       [2898., 3307., 3697., ..., 4598., 3850., 4938.]])

In [22]:
matrix.shape

(1797, 1797)

In [4]:
import scipy
from sklearn.datasets import load_boston
boston=load_boston()
x=boston.data
y=boston.target

c:\Users\rasua\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the

In [7]:
boston.DESCR

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000

In [8]:
x.shape

(506, 13)

In [9]:
y.shape

(506,)

In [12]:
#euclidean distance
a = np.array([[5],[4],[3],[1]])
b = np.array([[2],[0],[3],[0]])
c = np.array([[3],[2],[0],[1]])

In [15]:
dist_ab = np.linalg.norm(a-b)
dist_bc = np.linalg.norm(b-c)
dist_ca = np.linalg.norm(c-a)

In [16]:
dist_ab

5.0990195135927845

In [17]:
dist_bc

3.872983346207417

In [18]:
dist_ca

4.123105625617661

In [19]:
#cosine similarity (smaller the number, lesser the similarity and vice versa)
np.dot(a.T,b)/(np.linalg.norm(a)*np.linalg.norm(b))

array([[0.73789886]])

In [22]:
np.dot(c.T,a)/(np.linalg.norm(a)*np.linalg.norm(c))

array([[0.89817743]])

In [21]:
np.dot(b.T,c)/(np.linalg.norm(b)*np.linalg.norm(c))

array([[0.44474959]])

In [27]:
M = np.array([[2,1],[1,2]])

In [28]:
M

array([[2, 1],
       [1, 2]])

In [30]:
#Eigen values = lamda, eigen vectors
lamda,eigen_v = np.linalg.eig(M)

In [31]:
lamda

array([3., 1.])

In [32]:
eigen_v

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])